package day10;

/*
    Exception: An abnormal condition that arises in a code sequence at run-time.

    Whenever an exception arises, an object representing that exception is created
    and thrown in the method that caused the error.

    add();

    I can rethrow exception object from this method as well.

    Key points:
    1. Exceptions can be generated by Java run-time system or we can manually
    create them.
    2. Manually generated exceptions are typically used to report some error
    condition to the caller of the method.

    Five keywords for exception handling:
        try, catch, throw, throws, finally

    try ->
    catch ->
    throw -> E.g. throw new RuntimeException("my exception");
    throws ->
    finally ->

    General form:

    try {
        // code which may or may not give an exception
    }
    catch(ExceptionType1 exOb) { // ArithmeticException
        // handle the exception
    }
    catch(ExceptionType1 exOb) { // ArrayIndexOutOfBoundsException
        // handle the exception
    }
    finally {
        // this code executes even if exception occurs or not
    }
*/

public class ExceptionHandlingDemo {

}
